#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
 - name: user_name
   sudo: 'ALL=(ALL) NOPASSWD:ALL'
   shell: /bin/bash  
   ssh_authorized_keys:  
   - ssh-ed25519 AAAAC3NzaC1lZDI1NTEBBBAIL+O6cXczlSLnL0wZSMe6qRNKpfbdiG6BtYwCmvi5ctR user_name@Macmini.local
   
packages:
   - nginx
# Делаем обратный прокси на два домена prometheus и grafana 
write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          server_name prometheus.infratruct.ru;

          location / {
              proxy_pass http://10.2.0.20:9090;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

      server {
          listen 80;
          server_name grafana.infrastruct.ru;

          location / {
              proxy_pass http://10.2.0.20:3000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

runcmd:
   - sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
   - systemctl restart sshd
   - systemctl reload nginx
