- name: Allow connections on grafana port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3000
    jump: ACCEPT

- name: Deploy container
  community.docker.docker_container:
    name: "grafana"
    image: "grafana/grafana"
    restart_policy: always
    log_driver: "json-file"
    log_options:
      max-size: 1G
    ports:
      - "3000:3000"
