- name: Elasticsearch with SSL/TLS enabled
  hosts: nodes
  become: true
  roles:
    - role: ansible-elasticsearch
  vars:
    es_version: "8.17.3"
    es_package_file: "elasticsearch-8.17.3-arm64.deb"
    es_java_install: true
    es_config:
      node.name: "{{ node_name }}"
      cluster.name: "{{ cluster_name }}"
      network.host: 0.0.0.0
      discovery.seed_hosts: "{{ seed_hosts }}"
      cluster.initial_master_nodes: "{{ initial_master_nodes }}"
    es_heap_size: 512m
    es_api_basic_auth_username: "elastic"
    es_api_basic_auth_password: "changeme"
    es_api_sleep: 5
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_key: "files/certs/my-key.pem"
    es_ssl_certificate: "files/certs/my-cert.pem"
    es_ssl_certificate_authority: "files/certs/my-ca.pem"
    es_validate_certs: no
    es_users:
      native:
        elastic:
          password: "**********"
      file:
        es_admin:
          password: changeMe
          roles:
            - admin
        testUser:
          password: changeMeAlso!
          roles:
            - power_user
            - user
    es_roles:
      file:
        admin:
          cluster:
            - all
          indices:
            - names: '*'
          privileges:
            - all
          power_user:
            cluster:
              - monitor
            indices:
              - names: '*'
                privileges:
                  - all
          user:
            indices:
              - names: '*'
                privileges:
                  - read