- hosts: clients
  gather_facts: true
  become: true
  vars:
    fluentd_version: 5
    fluentd_lts: true
    fluentd_plugins:
      - name: fluent-plugin-elasticsearch
        version: '4.0.6'
        state: present
    #fluentd_service_name: td-agent
    fluentd_service_state: started
    fluentd_service_enabled: true
    fluentd_conf_sources: |
      <source>
        @type tail
        @id in_tail_container_logs
        path /var/lib/docker/containers/*/*.log
        pos_file /tmp/docker.pos
        read_from_head false
        tag docker.**
        skip_refresh_on_startup false
        refresh_interval 10s
        enable_watch_timer true
        enable_stat_watcher false
        <parse>
          @type json
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </parse>
      </source>
      <filter docker.**>
        @type record_transformer
        enable_ruby
        <record>
          hostname "#{Socket.gethostname}"
        </record>
      </filter>
      <match docker.**>
        @type forward
        @id forward_docker
        <server>
          host 192.168.1.71
          port 24224
        </server>
        <buffer>
          @type file
          path /tmp/fluentd.docker
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 2s
          retry_forever
          retry_max_interval 30
          chunk_limit_size 4M
          queue_limit_length 512
          overflow_action block
        </buffer>
      </match>
  roles:
    - ansible-role-fluentd

