---
- name: Install docker
  hosts: server3, test-vm1
  become: true
  roles:
    - role: docker
  tags: docker

- name: Install gitlab
  hosts: gitlab
  become: true
  roles:
    - roles: gitlab
  tags: gitlab

- name: Install runner
  hosts: server3
  become: true
  roles:
    - role: gitlab-runner
  tags: gitlab-runner

