- hosts: 192.168.1.91
  gather_facts: true
  vars:
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_elasticsearch_url: "http://localhost:9200"
    kibana_elasticsearch_username: "elastic"
    kibana_elasticsearch_password: "*************"
  roles:
    - ansible-role-kibana