- name: Install Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
  tags: prometheus

- name: Install Alertmanager
  hosts: alertmanager
  become: true
  roles:
    - alertmanager
  tags: alertmanager

- name: Install Grafana
  hosts: grafana
  become: true
  roles:
    - grafana
  tags: grafana

- name: Install Node exporter
  hosts: all
  become: true
  roles:
    - default_exporters
  tags: node_exporter
