- name: Install Prometheus
  hosts: monitoring
  become: true
  roles:
    - prometheus
  tags: prometheus

#- name: Install Alertmanager
#  hosts: monitoring
#  become: true
#  roles:
#    - alertmanager
#  tags: alertmanager

#- name: Install Grafana
#  hosts: monitoring
#  become: true
#  roles:
#    - grafana
#  tags: grafana

- name: Install Node exporter
  hosts: all
  become: true
  roles:
    - node-exporter
  tags: node_exporter
