#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
 - name: user_name
   sudo: 'ALL=(ALL) NOPASSWD:ALL'
   shell: /bin/bash  
   ssh_authorized_keys:  
   - ssh-ed25519 AAAAC3NzaC1lZDgsdsfI1NTEBBBAIL+O6cXczlSLnL0wZSMe6qRNKpfbdiG6BtYwCmvi5ctR user_name@Macmini.local
   
packages:

runcmd:
   - sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config
   - systemctl restart sshd

