---
- name: Install docker
  hosts: docker
  become: true
  roles:
    - role: docker
  tags: docker

- name: Install gitlab
  hosts: gitlab
  become: true
  roles:
    - role: gitlab
  tags: gitlab

- name: Install runner
  hosts: runner
  become: true
  roles:
    - role: gitlab-runner
  tags: gitlab-runner

- name: Install Prometheus
  hosts: prometheus
  become: true
  roles:
    - prometheus
  tags: prometheus

- name: Install Alertmanager
  hosts: alertmanager
  become: true
  roles:
    - alertmanager
  tags: alertmanager

- name: Install Grafana
  hosts: grafana
  become: true
  roles:
    - grafana
  tags: grafana

- name: Install Node exporter
  hosts: all
  become: true
  roles:
    - default_exporters
  tags: node_exporter

