- name: Pull GitLab Runner Docker image
  docker_image:
    name: gitlab/gitlab-runner
    tag: latest
    source: pull
  become: yes

- name: Run GitLab Runner Docker container
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - "/srv/gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: always
    privileged: yes
    env:
      CI_SERVER_URL: "{{ gitlab_url }}"
      REGISTRATION_TOKEN: "{{ gitlab_runner_token }}"
      RUNNER_EXECUTOR: "docker"
      RUNNER_TAG_LIST: "{{ gitlab_runner_tags }}"  
  become: yes

# - name: Register GitLab Runner
#   shell: |
#     docker exec -it gitlab-runner gitlab-runner register \
#       --non-interactive \
#       --url "{{ gitlab_url }}" \
#       --registration-token "{{ gitlab_runner_token }}" \
#       --executor "docker" \
#       --docker-image "docker:latest" \
#       --description "infra Docker Runner" \
#       --tag-list "{{ gitlab_runner_tags }}"
#   become: yes