- name: Add GitLab Runner repository using official script
  shell: |
    curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash
  become: yes

- name: Install GitLab Runner
  apt:
    name: gitlab-runner
    state: present
  become: yes

- name: Enable and start GitLab Runner service
  systemd:
    name: gitlab-runner
    enabled: yes
    state: started
  become: yes