- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present

# Установим библиотеку docker для питона
#- name: Install required Python packages for Docker
#  pip:
#    name: docker
#    state: present
#    executable: pip3
#  become: yes
#
#- name: Install required Python packages for Docker-compose
#  pip:
#    name: docker-compose
#    state: present
#    executable: pip3
#  become: yes
- name: Install required Python packages for Docker from APT
  apt:
    name:
      - python3-docker
      - docker-compose-plugin
    state: present
  become: yes


- name: Copy docker-compose.yml to the server
  copy:
    src: files/docker-compose.yml     
    dest: /srv/docker-compose.yml

- name: Start GitLab using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /srv
    state: present
   