- name: Pull GitLab Docker image
  docker_image:
    name: gitlab/gitlab-ce
    tag: latest
    source: pull
  become: yes

- name: Run GitLab Docker container
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
    restart_policy: always
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.infrastruct.ru'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['filatof@gmail.com']
        letsencrypt['auto_renew'] = true
        nginx['redirect_http_to_https'] = true
        nginx['listen_https'] = true
  become: yes

- name: Wait for GitLab to start
  wait_for:
    port: 443
    host: gitlab.infrastruct.ru
    timeout: 300
  become: yes

- name: Reconfigure GitLab to enable Let's Encrypt
  shell: |
    docker exec -it gitlab gitlab-ctl reconfigure
  become: yes
